import { Header } from "@/layouts/header";
import ReactQueryProvider from "@/lib/react-query";
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={comfortaa.className}>
          <Header />
          <main>{children}</main>
        </body>
      </ReactQueryProvider>
    </html>
  );
}
