import type { Metadata } from "next";
import { Rowdies } from "next/font/google";
import "./globals.css";

const rowdies = Rowdies({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rowdies.className}>{children}</body>
    </html>
  );
}
